### ISSUE TITLE
FB_ID is never used

### ISSUE THREAD

**Issue by brunetton** [antoniomsantos99/Valentine#1]
Hi, I just cloned your repo that promises to be exactly I wanted to do :) :+1: 
Si I noticed some little things; like this one: in config file template, there's a field `FB_ID` but this is never used in code (as the facebook token is sufficient to log in to Tinder API).

Maybe we should remove it from conf file template and README.md ? What do you think about ?

**Comment by antoniomsantos99** [comment]
Hi there! Sorry for being inactive but on holidays i didnt focus too much on coding.

I left the FB_ID field in the config file because it is used in the Pynder's repo examples and i was afraid that the lack of it could problems in the future. So far the bot looks stable enough so i also think it's a good idea to remove it from the config.

Thanks for the suggestion!
